basePath: /api
definitions:
  internal_api.CreateTaskRequest:
    properties:
      deleteSegments:
        description: 是否删除分段文件
        example: true
        type: boolean
      folder:
        description: 子文件夹
        example: movies
        type: string
      headers:
        description: 自定义HTTP头
        example:
        - 'User-Agent: Mozilla/5.0'
        items:
          type: string
        type: array
      id:
        description: 任务ID（可选，不提供时自动生成）
        example: 1
        type: integer
      localDir:
        description: 本地保存目录
        example: /downloads
        type: string
      name:
        description: 文件名
        example: video.mp4
        type: string
      proxy:
        description: 代理地址
        example: http://proxy.com:8080
        type: string
      type:
        description: 下载类型：m3u8/bilibili/direct
        example: m3u8
        type: string
      url:
        description: 下载URL
        example: https://example.com/a.m3u8
        type: string
    required:
    - localDir
    - name
    - type
    - url
    type: object
  internal_api.CreateTaskResponse:
    properties:
      id:
        description: 任务ID
        example: 1
        type: integer
      message:
        description: 响应消息
        example: Task enqueued successfully
        type: string
    type: object
  internal_api.ErrorResponse:
    properties:
      error:
        description: 错误信息
        example: invalid request
        type: string
    type: object
  internal_api.StopTaskResponse:
    properties:
      message:
        description: 响应消息
        example: Task stopped
        type: string
    type: object
  internal_api.UpdateConfigRequest:
    properties:
      maxRunner:
        description: 最大并发下载数
        example: 3
        type: integer
      proxy:
        description: 代理服务器地址
        example: http://proxy.com:8080
        type: string
    type: object
  internal_api.UpdateConfigResponse:
    properties:
      message:
        description: 响应消息
        example: Config updated
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@mediago.local
    name: API Support
    url: https://github.com/caorushizi/mediago-core
  description: |-
    MediaGo 多任务下载系统 API 文档
    支持 M3U8、Bilibili、Direct 三种下载类型
    提供任务管理、配置更新、实时事件推送等功能
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: MediaGo Downloader API
  version: "1.0"
paths:
  /config:
    post:
      consumes:
      - application/json
      description: 更新系统配置，包括最大并发下载数和代理设置
      parameters:
      - description: 配置参数
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/internal_api.UpdateConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 配置更新成功
          schema:
            $ref: '#/definitions/internal_api.UpdateConfigResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/internal_api.ErrorResponse'
      summary: 更新系统配置
      tags:
      - Config
  /events:
    get:
      description: |-
        订阅服务器推送事件（SSE），实时接收下载任务的状态更新
        事件类型包括：download-start, download-success, download-failed, download-stop, download-progress, download-ready, download-message
      produces:
      - text/event-stream
      responses:
        "200":
          description: SSE 事件流
          schema:
            type: string
      summary: SSE 事件流
      tags:
      - Events
  /tasks:
    post:
      consumes:
      - application/json
      description: |-
        创建一个新的下载任务并加入队列
        支持 M3U8、Bilibili、Direct 三种下载类型
      parameters:
      - description: 下载任务参数
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/internal_api.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 任务创建成功
          schema:
            $ref: '#/definitions/internal_api.CreateTaskResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/internal_api.ErrorResponse'
      summary: 创建下载任务
      tags:
      - Tasks
  /tasks/{id}/stop:
    post:
      consumes:
      - application/json
      description: 停止指定ID的下载任务
      parameters:
      - description: 任务ID
        example: 1
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 任务停止成功
          schema:
            $ref: '#/definitions/internal_api.StopTaskResponse'
        "400":
          description: 无效的任务ID
          schema:
            $ref: '#/definitions/internal_api.ErrorResponse'
        "404":
          description: 任务不存在
          schema:
            $ref: '#/definitions/internal_api.ErrorResponse'
      summary: 停止下载任务
      tags:
      - Tasks
schemes:
- http
- https
swagger: "2.0"
tags:
- description: 下载任务管理相关接口
  name: Tasks
- description: 系统配置相关接口
  name: Config
- description: 实时事件推送相关接口
  name: Events
