basePath: /api
definitions:
  caorushizi_cn_mediago_internal_core.DownloadType:
    enum:
    - m3u8
    - bilibili
    - direct
    type: string
    x-enum-varnames:
    - TypeM3U8
    - TypeBilibili
    - TypeDirect
  caorushizi_cn_mediago_internal_core.TaskInfo:
    properties:
      error:
        description: 错误信息（如果有）
        type: string
      id:
        description: 任务ID
        type: integer
      isLive:
        description: 是否为直播流
        type: boolean
      name:
        description: 文件名
        type: string
      percent:
        description: 完成百分比
        type: number
      speed:
        description: 下载速度
        type: string
      status:
        allOf:
        - $ref: '#/definitions/caorushizi_cn_mediago_internal_core.TaskStatus'
        description: 任务状态
      type:
        allOf:
        - $ref: '#/definitions/caorushizi_cn_mediago_internal_core.DownloadType'
        description: 下载类型
      url:
        description: 下载URL
        type: string
    type: object
  caorushizi_cn_mediago_internal_core.TaskStatus:
    enum:
    - pending
    - downloading
    - success
    - failed
    - stopped
    type: string
    x-enum-comments:
      StatusDownloading: 下载中
      StatusFailed: 失败
      StatusPending: 等待中
      StatusStopped: 已停止
      StatusSuccess: 成功完成
    x-enum-descriptions:
    - 等待中
    - 下载中
    - 成功完成
    - 失败
    - 已停止
    x-enum-varnames:
    - StatusPending
    - StatusDownloading
    - StatusSuccess
    - StatusFailed
    - StatusStopped
  internal_api.CreateTaskRequest:
    properties:
      deleteSegments:
        description: 是否删除分段文件
        example: true
        type: boolean
      folder:
        description: 子文件夹
        example: movies
        type: string
      headers:
        description: 自定义HTTP头
        example:
        - 'User-Agent: Mozilla/5.0'
        items:
          type: string
        type: array
      id:
        description: 任务ID（可选，不提供时自动生成）
        example: 1
        type: integer
      localDir:
        description: 本地保存目录
        example: /downloads
        type: string
      name:
        description: 文件名
        example: video.mp4
        type: string
      proxy:
        description: 代理地址
        example: http://proxy.com:8080
        type: string
      type:
        description: 下载类型：m3u8/bilibili/direct
        example: m3u8
        type: string
      url:
        description: 下载URL
        example: https://example.com/a.m3u8
        type: string
    required:
    - localDir
    - name
    - type
    - url
    type: object
  internal_api.CreateTaskResponse:
    properties:
      id:
        description: 任务ID
        example: 1
        type: integer
      message:
        description: 响应消息
        example: Task enqueued successfully
        type: string
    type: object
  internal_api.ErrorResponse:
    properties:
      error:
        description: 错误信息
        example: invalid request
        type: string
    type: object
  internal_api.StopTaskResponse:
    properties:
      message:
        description: 响应消息
        example: Task stopped
        type: string
    type: object
  internal_api.UpdateConfigRequest:
    properties:
      maxRunner:
        description: 最大并发下载数
        example: 3
        type: integer
      proxy:
        description: 代理服务器地址
        example: http://proxy.com:8080
        type: string
    type: object
  internal_api.UpdateConfigResponse:
    properties:
      message:
        description: 响应消息
        example: Config updated
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@mediago.local
    name: API Support
    url: https://github.com/caorushizi/mediago-core
  description: |-
    MediaGo 多任务下载系统 API 文档
    支持 M3U8、Bilibili、Direct 三种下载类型
    提供任务管理、配置更新、实时事件推送等功能
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: MediaGo Downloader API
  version: "1.0"
paths:
  /config:
    post:
      consumes:
      - application/json
      description: 更新系统配置，包括最大并发下载数和代理设置
      parameters:
      - description: 配置参数
        in: body
        name: config
        required: true
        schema:
          $ref: '#/definitions/internal_api.UpdateConfigRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 配置更新成功
          schema:
            $ref: '#/definitions/internal_api.UpdateConfigResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/internal_api.ErrorResponse'
      summary: 更新系统配置
      tags:
      - Config
  /events:
    get:
      description: |-
        订阅服务器推送事件（SSE），实时接收下载任务的状态变更通知
        事件类型包括：download-start（任务开始）, download-success（任务成功）, download-failed（任务失败）, download-stop（任务停止）
        注意：不包含进度更新事件，如需获取下载进度，请通过 GET /api/tasks/{id} 接口轮询
      produces:
      - text/event-stream
      responses:
        "200":
          description: SSE 事件流
          schema:
            type: string
      summary: SSE 事件流
      tags:
      - Events
  /healthz:
    delete:
      description: 服务健康检查接口，用于监控服务是否正常运行
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 健康检查
      tags:
      - Health
    get:
      description: 服务健康检查接口，用于监控服务是否正常运行
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 健康检查
      tags:
      - Health
    head:
      description: 服务健康检查接口，用于监控服务是否正常运行
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 健康检查
      tags:
      - Health
    options:
      description: 服务健康检查接口，用于监控服务是否正常运行
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 健康检查
      tags:
      - Health
    patch:
      description: 服务健康检查接口，用于监控服务是否正常运行
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 健康检查
      tags:
      - Health
    post:
      description: 服务健康检查接口，用于监控服务是否正常运行
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 健康检查
      tags:
      - Health
    put:
      description: 服务健康检查接口，用于监控服务是否正常运行
      produces:
      - text/plain
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 健康检查
      tags:
      - Health
  /tasks:
    get:
      consumes:
      - application/json
      description: 获取所有任务的状态和进度信息列表
      produces:
      - application/json
      responses:
        "200":
          description: 任务列表
          schema:
            items:
              $ref: '#/definitions/caorushizi_cn_mediago_internal_core.TaskInfo'
            type: array
      summary: 获取所有任务状态
      tags:
      - Tasks
    post:
      consumes:
      - application/json
      description: |-
        创建一个新的下载任务并加入队列
        支持 M3U8、Bilibili、Direct 三种下载类型
      parameters:
      - description: 下载任务参数
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/internal_api.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 任务创建成功
          schema:
            $ref: '#/definitions/internal_api.CreateTaskResponse'
        "400":
          description: 请求参数错误
          schema:
            $ref: '#/definitions/internal_api.ErrorResponse'
      summary: 创建下载任务
      tags:
      - Tasks
  /tasks/{id}:
    get:
      consumes:
      - application/json
      description: 获取指定ID的任务状态和进度信息
      parameters:
      - description: 任务ID
        example: 1
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 任务信息
          schema:
            $ref: '#/definitions/caorushizi_cn_mediago_internal_core.TaskInfo'
        "400":
          description: 无效的任务ID
          schema:
            $ref: '#/definitions/internal_api.ErrorResponse'
        "404":
          description: 任务不存在
          schema:
            $ref: '#/definitions/internal_api.ErrorResponse'
      summary: 获取任务状态
      tags:
      - Tasks
  /tasks/{id}/stop:
    post:
      consumes:
      - application/json
      description: 停止指定ID的下载任务
      parameters:
      - description: 任务ID
        example: 1
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 任务停止成功
          schema:
            $ref: '#/definitions/internal_api.StopTaskResponse'
        "400":
          description: 无效的任务ID
          schema:
            $ref: '#/definitions/internal_api.ErrorResponse'
        "404":
          description: 任务不存在
          schema:
            $ref: '#/definitions/internal_api.ErrorResponse'
      summary: 停止下载任务
      tags:
      - Tasks
schemes:
- http
- https
swagger: "2.0"
tags:
- description: 健康检查相关接口
  name: Health
- description: 下载任务管理相关接口
  name: Tasks
- description: 系统配置相关接口
  name: Config
- description: 实时事件推送相关接口
  name: Events
